version: '3.8'
services:


  web:
    container_name: ${APP_NAME}-web
    build: ./app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54320:5432"


volumes:
  postgres_data: