version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    env_file:
      - ./app/.env.dev
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    restart: always
    ports:
      - "54320:5432"


volumes:
  postgres_data: