version: '3.8'
services:
  web:
    container_name: ${APP_NAME}-web
    build: ./bookstore
    command: python manage.py run -h 0.0.0.0
    #    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./bookstore:/app
    ports:
      - ${APP_PORT}:5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - mailhog
  db:
    container_name: ${APP_NAME}-db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54320:5432"
  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}-mailhog
    restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
  pgadmin:
    container_name: ${APP_NAME}-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin-data: