version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: