version: '3.8'

services:
  web:
    container_name: ${APP_NAME}-web-prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db-prod
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: