"""empty message

Revision ID: 1b3ae9024148
Revises: b77aa623a798
Create Date: 2023-03-20 12:54:55.111170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b3ae9024148"
down_revision = "b77aa623a798"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("image_main_id", sa.Integer(), nullable=True))
    op.drop_constraint("books_main_image_id_fkey", "books", type_="foreignkey")
    op.create_foreign_key(None, "books", "images_main", ["image_main_id"], ["id"])
    op.drop_column("books", "main_image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column("main_image_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "books", type_="foreignkey")
    op.create_foreign_key(
        "books_main_image_id_fkey", "books", "images_main", ["main_image_id"], ["id"]
    )
    op.drop_column("books", "image_main_id")
    # ### end Alembic commands ###
