"""empty message

Revision ID: 64a4821cab43
Revises: 82e0e4b0716e
Create Date: 2023-03-18 14:28:57.440101

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64a4821cab43"
down_revision = "82e0e4b0716e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
