"""empty message

Revision ID: 70ea6216ff1f
Revises: b767e054e878
Create Date: 2023-03-20 15:11:47.792382

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70ea6216ff1f"
down_revision = "b767e054e878"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
