"""empty message

Revision ID: 76cecb84076c
Revises: acfcc0307a60
Create Date: 2023-03-20 13:33:54.679808

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76cecb84076c"
down_revision = "acfcc0307a60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("image_main_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "images_main", ["image_main_id"], ["id"])
    op.drop_constraint("images_main_book_id_fkey", "images_main", type_="foreignkey")
    op.drop_column("images_main", "book_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images_main",
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "images_main_book_id_fkey", "images_main", "books", ["book_id"], ["id"]
    )
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "image_main_id")
    # ### end Alembic commands ###
