"""empty message

Revision ID: 7ede4678d122
Revises: 64a4821cab43
Create Date: 2023-03-18 15:22:10.894387

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ede4678d122"
down_revision = "64a4821cab43"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("categories_level_idx", table_name="categories")
    op.drop_index("categories_lft_idx", table_name="categories")
    op.drop_index("categories_rgt_idx", table_name="categories")
    op.drop_constraint("categories_parent_id_fkey", "categories", type_="foreignkey")
    op.create_foreign_key(None, "categories", "categories", ["parent_id"], ["id"])
    op.drop_column("categories", "lft")
    op.drop_column("categories", "rgt")
    op.drop_column("categories", "level")
    op.drop_column("categories", "tree_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("tree_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "categories",
        sa.Column("rgt", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "categories",
        sa.Column("lft", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key(
        "categories_parent_id_fkey",
        "categories",
        "categories",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("categories_rgt_idx", "categories", ["rgt"], unique=False)
    op.create_index("categories_lft_idx", "categories", ["lft"], unique=False)
    op.create_index("categories_level_idx", "categories", ["level"], unique=False)
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
