"""empty message

Revision ID: 82e0e4b0716e
Revises: a48eeb28c3e4
Create Date: 2023-03-18 14:24:40.136037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82e0e4b0716e"
down_revision = "a48eeb28c3e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=400), nullable=True),
        sa.Column("tree_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("lft", sa.Integer(), nullable=False),
        sa.Column("rgt", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("categories_level_idx", "categories", ["level"], unique=False)
    op.create_index("categories_lft_idx", "categories", ["lft"], unique=False)
    op.create_index("categories_rgt_idx", "categories", ["rgt"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_table(
        "books_categories",
        sa.Column("books", sa.Integer(), nullable=True),
        sa.Column("categories", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["books"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categories"],
            ["categories.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books_categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index("categories_rgt_idx", table_name="categories")
    op.drop_index("categories_lft_idx", table_name="categories")
    op.drop_index("categories_level_idx", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
