"""empty message

Revision ID: 922920bfc54f
Revises: 76cecb84076c
Create Date: 2023-03-20 14:21:18.576243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "922920bfc54f"
down_revision = "76cecb84076c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("books_image_main_id_fkey", "books", type_="foreignkey")
    op.drop_column("books", "image_main_id")
    op.add_column("images_main", sa.Column("book_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "images_main", "books", ["book_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "images_main", type_="foreignkey")
    op.drop_column("images_main", "book_id")
    op.add_column(
        "books",
        sa.Column("image_main_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "books_image_main_id_fkey", "books", "images_main", ["image_main_id"], ["id"]
    )
    # ### end Alembic commands ###
