"""empty message

Revision ID: 961ea79eebf2
Revises: f8a840e17161
Create Date: 2023-04-02 17:45:33.407902

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "961ea79eebf2"
down_revision = "f8a840e17161"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_confirmed", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.drop_column("users", "email_confirmed")
    # ### end Alembic commands ###
