"""empty message

Revision ID: a09b230b4f05
Revises: 922920bfc54f
Create Date: 2023-03-20 14:28:20.510006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a09b230b4f05"
down_revision = "922920bfc54f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("image_path", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "image_path")
    # ### end Alembic commands ###
