"""empty message

Revision ID: aa43b5cf2b46
Revises: c9fa7039751a
Create Date: 2023-03-20 12:36:50.160154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa43b5cf2b46"
down_revision = "c9fa7039751a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books_authors",
        sa.Column("books", sa.Integer(), nullable=True),
        sa.Column("authors", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authors"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["books"],
            ["books.id"],
        ),
    )
    op.add_column("books", sa.Column("annotation", sa.Text(), nullable=True))
    op.add_column("books", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("number_of_pages", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("size", sa.String(length=128), nullable=True))
    op.add_column("books", sa.Column("weight", sa.Integer(), nullable=True))
    op.drop_constraint("books_author_id_fkey", "books", type_="foreignkey")
    op.drop_column("books", "author_id")
    op.add_column("images", sa.Column("is_main", sa.Boolean(), nullable=True))
    op.drop_column("images", "is_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column("is_title", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("images", "is_main")
    op.add_column(
        "books",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "books_author_id_fkey", "books", "authors", ["author_id"], ["id"]
    )
    op.drop_column("books", "weight")
    op.drop_column("books", "size")
    op.drop_column("books", "number_of_pages")
    op.drop_column("books", "year")
    op.drop_column("books", "annotation")
    op.drop_table("books_authors")
    # ### end Alembic commands ###
