"""empty message

Revision ID: b767e054e878
Revises: a09b230b4f05
Create Date: 2023-03-20 14:34:02.615667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b767e054e878"
down_revision = "a09b230b4f05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("images_main")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images_main",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name="images_main_book_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="images_main_pkey"),
    )
    # ### end Alembic commands ###
