"""empty message

Revision ID: b77aa623a798
Revises: aa43b5cf2b46
Create Date: 2023-03-20 12:53:24.083682

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b77aa623a798"
down_revision = "aa43b5cf2b46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images_main",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("books", sa.Column("main_image_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "images_main", ["main_image_id"], ["id"])
    op.drop_column("images", "is_main")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("is_main", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "main_image_id")
    op.drop_table("images_main")
    # ### end Alembic commands ###
