"""empty message

Revision ID: c404dbc8a493
Revises: f0e3052a44a7
Create Date: 2023-03-25 07:23:32.223124

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c404dbc8a493"
down_revision = "f0e3052a44a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("carts_books")
    op.drop_table("carts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts_books",
        sa.Column("cart_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name="carts_books_book_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name="carts_books_cart_id_fkey"
        ),
        sa.PrimaryKeyConstraint("cart_id", "book_id", name="carts_books_pkey"),
    )
    op.create_table(
        "carts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="carts_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="carts_pkey"),
    )
    # ### end Alembic commands ###
