"""empty message

Revision ID: c9fa7039751a
Revises: 7ede4678d122
Create Date: 2023-03-18 16:23:17.942501

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9fa7039751a"
down_revision = "7ede4678d122"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
