"""empty message

Revision ID: cefb14652349
Revises: 1b3ae9024148
Create Date: 2023-03-20 13:01:04.169274

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cefb14652349"
down_revision = "1b3ae9024148"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
