"""empty message

Revision ID: f0e3052a44a7
Revises: c891e0a23a4b
Create Date: 2023-03-24 21:33:23.348056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f0e3052a44a7"
down_revision = "c891e0a23a4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
